### PR TITLE
Restrict SSLv3 clients to RC4 to protect against POODLE on SSLv3 (fixes #40)

### LINKED ISSUE #40: CBC ciphers still being used for SSLv3?
cc: @gkaemmer

### PR DESCRIPTION
**Pull request by fancyremarker**
@aaw: I couldn't find authoritative documentation on how to disallow block ciphers (CBC) with SSLv3, so my approach was to take our existing cipher list, and then additionally disallow any non-RC4 ciphers supported by SSLv3:

```
openssl ciphers -v $EXISTING_CIPHERS | grep SSLv3 | grep -v RC4
```

Does this seem sane? Also, note that a test executing either of the following two lines fails:

```
local_s_client -cipher "AES" -tls1
local_s_client -cipher "AES" -tls1_1
```

I think this means that TLSv1.1 is restricted to RC4 per this change, but I'm not sure how problematic that is. (How many clients have TLSv1.1 but not TLSv1.2?)

### CODE REVIEW

**Comment by fancyremarker** [comment]
Fixes #40.

**Comment by aaw** [comment]
This might be a little too aggressive: I think that criteria like `!ECDHE-ECDSA-AES256-SHA` will actually disallow strong, common TLS 1.2 suites like `ECDHE-ECDSA-AES256-SHA384`. At least, it seemed to in my tests. Maybe we _just_ want to append `!SSLv3+AES`? In my testing, that does what we want and running `s_client` with `-ssl3` against the resulting config negotiates `ECDHE-RSA-RC4-SHA` for me, in addition to passing the bats tests in this PR.

**Comment by fancyremarker** [comment]
Thanks! Updated.

**Comment by fancyremarker** [comment]
FYI: This change results in a passing test on Tinfoil, but still a downgrade on Qualys (they appear to be checking for a specific RC4 cipher variant with SSLv3, instead of correctly checking that only RC4 ciphers are allowed with SSLv3).

**Pull request merged**
