### PR TITLE
Hostname filtering

### PR DESCRIPTION
**Pull request by krallin**
See: https://github.com/aptible/api.aptible.com/pull/572
See: https://github.com/aptible/sweetness/pull/947

cc @fancyremarker

### CODE REVIEW

**Comment by krallin** [comment]
TODO:

- [ ] Serve a descriptive error page when using the wrong domain

**Comment by krallin** [comment]
>> Serve a descriptive error page when using the wrong domain
>
>Should we dynamically write out a few error pages for common error cases (currently just bad upstream / unacceptable Host header), using the existing error page as a template, but with placeholder text for the error title and message?

I think so. Did you have other errors in mind, or just those two?

**Comment by fancyremarker** [comment]
Those are the only two.

**Comment by krallin** [comment]
This was pulled in as part of #96.

**Pull request closed without merging**
